services:
  media-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:z
      - ~/.m2:/root/.m2
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
      
      
    # depends_on:
    #   - db